import { useState } from 'react';
import { ErrorAlert } from '../../components/feedback/ErrorAlert';
import { getApiError } from '../../services/api';
import { useUpdateMediaMutation } from './mediaApi';
import { normalizeTags } from '../upload/validation';

export function EditMediaForm({ media, onDone }) {
  const [values, setValues] = useState({ title: media.title, description: media.description || '', tags: media.tags?.join(', ') || '' }); const [errors, setErrors] = useState({}); const [update, state] = useUpdateMediaMutation();
  const submit = async (event) => { event.preventDefault(); const next = {}; const tags = normalizeTags(values.tags); if (values.title.trim().length < 2 || values.title.trim().length > 120) next.title = 'Title must be between 2 and 120 characters.'; if (values.description.length > 2000) next.description = 'Description cannot exceed 2,000 characters.'; if (tags.length > 10 || tags.some((tag) => tag.length > 30)) next.tags = 'Use up to 10 tags, each no longer than 30 characters.'; setErrors(next); if (Object.keys(next).length) return; try { await update({ id: media._id, title: values.title.trim(), description: values.description.trim(), tags }).unwrap(); onDone(); } catch { /* state below */ } };
  return <form className="edit-form" onSubmit={submit} noValidate><EditField label="Title" name="title" value={values.title} error={errors.title} onChange={(event) => setValues({ ...values, title: event.target.value })} /><EditField label="Description" name="description" value={values.description} error={errors.description} textarea onChange={(event) => setValues({ ...values, description: event.target.value })} /><EditField label="Tags" name="tags" value={values.tags} error={errors.tags} onChange={(event) => setValues({ ...values, tags: event.target.value })} /><ErrorAlert message={state.error && getApiError(state.error, 'Changes could not be saved.')} /><div className="form-actions"><button className="button button--secondary" type="button" onClick={onDone}>Cancel</button><button className="button" disabled={state.isLoading}>{state.isLoading ? 'Saving…' : 'Save changes'}</button></div></form>;
}
function EditField({ label, name, value, error, textarea, onChange }) { const Input = textarea ? 'textarea' : 'input'; return <div className="field"><label htmlFor={`edit-${name}`}>{label}</label><Input id={`edit-${name}`} value={value} onChange={onChange} aria-invalid={Boolean(error)} aria-describedby={error ? `edit-${name}-error` : undefined} />{error && <span className="field__error" id={`edit-${name}-error`}>{error}</span>}</div>; }
